### ISSUE TITLE
Export by NR plugin errors on script with iviews

### ISSUE THREAD

**Issue by JoeAggie** [sschwartzman/newrelic-synthetics-sebuilder#11]
Hello, Daniel pointed me this direction.

My company is trying a POC with NR synthetics. Selenium Builder 2.3.5 is not able to grab an identifier for an iframe for switchToFrame. This causes an error on export with the New Relic Synthetics (WebDriver JS). The error popup window titled "JavaScript Application" is "ReferenceError: thisstepentifier is not defined". With FireFox 43 and above, Selenium Builder >= 3.0.5 is required as plugin signing is now mandatory. SB 3.0.5 does not display "Run test locally" for some reason. I downgraded to the same version of FF 33.1.1 that Daniel had and plugged SB 2.3.5 back in to restore the local test run functionality. I know the SB script is incomplete without an iframe identifier but the script DOES run locally if I open it and run it immediately without any other actions, otherwise it will hang up on the switchToFrame step. Daniel said it should export regardless and to open this ticket and you'd ping me for details. So here it is!

Thanks,
Robert

**Comment by sschwartzman** [comment]
Hi Robert,

In order to export, the step will have to be complete. In recording, can you find a frame identifier to tie it to? You can use "inspect element" in Firefox to find the name of the frame in question.

The failure to export is not something that is controlled by the New Relic plugin, but rather by Se-Builder. So I'm going to go ahead and close this ticket if that's alright.

Also you were right in using the older version of FF and SB for now. I'm waiting for 3.x to be feature-complete before porting the plugin to it. 

Thanks,
Seth

**Comment by JoeAggie** [comment]
Okay, thanks, Seth. Daniel also wanted to confirm the versioning choices.

Thanks,
Robert

On Jan 21, 2016 9:20 PM, Seth Schwartzman <notifications@github.com> wrote:

Hi Robert,

In order to export, the step will have to be complete. In recording, can you find a frame identifier to tie it to? You can use "inspect element" in Firefox to find the name of the frame in question.

The failure to export is not something that is controlled by the New Relic plugin, but rather by Se-Builder. So I'm going to go ahead and close this ticket if that's alright.

Also you were right in using the older version of FF and SB for now. I'm waiting for 3.x to be feature-complete before porting the plugin to it.

Thanks,
Seth
